#!/bin/zsh
all=true
run_test() {
    testname=$1
    if [ -f $testname.diff ];
    then
        rm $testname.diff
    fi
    echo -e "\033[1;33m\nRunning $testname\033[0m">>&testall.out
    if [ $all = true ]; 
    then
        ./$testname >>& testall.out
    else
        ./$testname
    fi
    if [ $? -ne 0 ] 
    then
        if [ $all = false ]; then
            echo
        fi
        echo -e "\033[1;31m$testname Failed\033[0m"
    else
        if [ $all = false ]; then
            echo
        fi
        echo -e "\033[1;32m$testname Passed\033[0m"
    fi
    #if [ $all = true ]; then
    cat $testname.diff >> testall.diff
    cat $testname.mem >> testall.mem
    #fi
}
rm -f testall.out testall.diff
if [ -f testall.diff ];
then 
    rm testall.diff
fi
if [ $# -eq 0 ]; then
    run_test test_basic_commands
    run_test test_redirect_output
    run_test test_redirect_input
    run_test test_redirect_error
    #run_test test_redirect_append
    #run_test test_redirect_outerr
    #run_test test_redirect_multiple
    run_test test_pipe
    #run_test test_pipe_redirect
    run_test test_zombie
    run_test test_exit
    #run_test test_quotes
    run_test test_escape
    run_test test_setenv
    #run_test test_unsetenv
    run_test test_source
    #run_test test_cd
    #run_test test_command_substitution
    #run_test test_process_substitution
else
    all=false
    run_test $1
fi
