#!/bin/zsh
diffFile=test_escape.diff
memFile=test_escape.mem
pass=true
check() {
    if [ $2 -ne 0 ] 
    then
        if [ $2 -eq 124 ] 
        then
            echo -e "\033[1;31m Timed out on command $1\033[0m" >> $diffFile 
        fi
        echo -e "\033[1;31m Failed to run $1\033[0m"
        pass=false
    else
        grep -E "lost: [1-9]" <(valgrind --show-leak-kinds=all --leak-check=full --track-origins=yes ../../shell  <<< $1 2>&1) >>& $memFile
        if [ $? -eq 0 ]
        then
            pass=false
            echo -e "\033[1;31m Failed to run $1\033[0m"
        else
        echo -e "\033[1;32m $1 ran successfully\033[0m"
        fi
    fi
}
echo -e "\033[1;4;93m\ttest escape\033[0m"
echo -e "\033[1;4;93m\ttest escape\033[0m" > $diffFile >> $memFile
shell_in=$'echo h\zello'
zsh_in=$'echo h\zello'
echo Processing Command: $shell_in>>$diffFile >> $memFile
timeout -k 1 2.5 diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; ) <(../../shell <<< $shell_in 2>&1; ) >>& $diffFile
check $shell_in $?
shell_in=$'echo h\ ello'
zsh_in=$'echo h\ ello'
echo Processing Command: $shell_in>>$diffFile>> $memFile
timeout -k 1 2.5 diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; ) <(../../shell <<< $shell_in 2>&1; ) >>& $diffFile
check $shell_in $?
#special characters
shell_in=$'echo h\'\>\|\$\<\&\ \' ello'
zsh_in=$'echo h\'\>\|\$\<\&\ \' ello'
echo Processing Command: $shell_in>>$diffFile>> $memFile
timeout -k 1 2.5 diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; ) <(../../shell <<< $shell_in 2>&1; ) >>& $diffFile
check $shell_in $?
if [ $pass = true ]
then
    exit 0
else
    exit 1
fi
