#!/bin/zsh
diffFile=test_redirect_multiple.diff
pass=true
check() {
    if [ $2 -ne 0 ] 
    then
        echo -e "\033[1;31m Failed to run $1\033[0m"
        pass=false
    else
        echo -e "\033[1;32m $1 ran successfully\033[0m"
    fi
}
echo -e "\033[1;4;93m\ttest redirect multiple\033[0m"
echo -e "\033[1;4;93m\ttest redirect multiple\033[0m" > $diffFile
shell_in=$'grep test < testall> out1'
zsh_in=$'grep test < testall > out2'
rm -f out*
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out2) <(../../shell <<< $shell_in 2>&1; cat out1) >>& $diffFile
check $shell_in $?
shell_in=$'cat < testall < test_redirect_input> out1'
zsh_in=$'cat < testall < test_redirect_input > out2'
rm -f out*
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out2) <(../../shell <<< $shell_in 2>&1; cat out1) >>& $diffFile
check $shell_in $?
shell_in=$'grep < testall < test_redirect_input> out1 2> out2'
zsh_in=$'grep < testall < test_redirect_input > out3 2> out4'
rm -f out*
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out[3-4]) <(../../shell <<< $shell_in 2>&1; cat out[1-2]) >>& $diffFile
check $shell_in $?
if [ $pass = true ]
then
    exit 0
else
    exit 1
fi
