#!/bin/zsh
diffFile=test_pipe_redirect.diff
pass=true
check() {
    if [ $2 -ne 0 ] 
    then
        echo -e "\033[1;31m Failed to run $1\033[0m"
        pass=false
    else
        echo -e "\033[1;32m $1 ran successfully\033[0m"
    fi
}
echo -e "\033[1;4;93m\ttest pipe redirect\033[0m"
echo -e "\033[1;4;93m\ttest pipe redirect\033[0m" > $diffFile
shell_in=$'ls | cat < testall'
zsh_in=$'ls | cat < testall'
rm -f out*
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1;) <(../../shell <<< $shell_in 2>&1;) >>& $diffFile
check $shell_in $?
shell_in=$'cat testall > out1 | grep a < test_redirect_input >> out1 2> out2'
zsh_in=$'cat testall > out3 | grep a < test_redirect_input >> out3 2> out4'
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out[3-4]) <(../../shell <<< $shell_in 2>&1; cat out[1-2]) >>& $diffFile
check $shell_in $?
shell_in=$'ls -al | grep test < testall > out1 >> out2 | wc >& out3 >>& out4'
zsh_in=$'ls -al | grep test < testall > out5 >> out6 | wc >& out7 >>& out8'
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out[5-8]) <(../../shell <<< $shell_in 2>&1; cat out[1-4]) >>& $diffFile
check $shell_in $?
if [ $pass = true ]
then
    exit 0
else 
    exit 1
fi
