#!/bin/zsh
all=true
run_test() {
    testname=$1
    if [ -f $testname.diff ];
    then
        rm $testname.diff
    fi
    echo -e "\033[1;33m\nRunning $testname\033[0m">>&testall.out
    if [ $all = true ]; 
    then
        ./$testname >>& testall.out
    else
        ./$testname
    fi
    if [ $? -ne 0 ] 
    then
        if [ $all = false ]; then
            echo
        fi
        echo -e "\033[1;31m$testname Failed\033[0m"
    else
        if [ $all = false ]; then
            echo
        fi
        echo -e "\033[1;32m$testname Passed\033[0m"
    fi
    cat $testname.diff >> testall.diff
}
rm -f testall.out testall.diff
if [ -f testall.diff ];
then 
    rm testall.diff
fi
if [ $# -eq 0 ]; then
    run_test test_basic_commands
    run_test test_redirect_input
    run_test test_redirect_output
else
    all=false
    run_test $1
fi
