#!/bin/zsh
diffFile=test_redirect_outerr.diff
pass=true
check() {
    if [ $2 -ne 0 ] 
    then
        echo -e "\033[1;31m Failed to run $1\033[0m"
        pass=false
    else
        echo -e "\033[1;32m $1 ran successfully\033[0m"
    fi
}
echo -e "\033[1;4;93m\ttest redirect outerr\033[0m"
echo -e "\033[1;4;93m\ttest redirect outerr\033[0m" > $diffFile
shell_in=$'grep hello >& out1'
zsh_in=$'grep hello >& out2'
rm -f out*
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out2) <(../shell <<< $shell_in 2>&1; cat out1) >>& $diffFile
check $shell_in $?
shell_in=$'echo hello >& out1\n echo hello >>& out1'
zsh_in=$'echo hello >& out2\n echo hello >>& out2'
rm -f out*
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out2) <(../shell <<< $shell_in 2>&1; cat out1) >>& $diffFile
check $shell_in $?
shell_in=$'cat hello testall >>& out1 >>& out3'
zsh_in=$'cat hello testall >>& out2 >>& out4'
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out2 out4) <(../shell <<< $shell_in 2>&1; cat out1 out3) >>& $diffFile
check $shell_in $?
if [ $pass = true ]
then
    exit 0
else
    exit 1
fi
