#!/bin/zsh
diffFile=test_process_substitution.diff
pass=true
run_cmd() {
    #echo Processing Command: $1
    echo Processing Command: $1 >>& $diffFile
    diff --color -u <(/bin/zsh <<< $1 2>&1) <(../shell <<< $1 2>&1) >>& $diffFile
    check $1 $?
}
check() {
    if [ $2 -ne 0 ] 
    then
        echo -e "\033[1;31m Failed to run $1\033[0m"
        pass=false
    else
        echo -e "\033[1;32m $1 ran successfully\033[0m"
    fi
}
echo -e "\033[1;4;93m\ttest process substitution\033[0m"
echo -e "\033[1;4;93m\ttest process substitution\033[0m" > $diffFile

#write process substitution
input_str=$'cat <(ls)'
run_cmd $input_str
#read process substitution
input_str=$'cat testall > >(grep t | grep a | echo a)'
run_cmd $input_str
#diff
input_str=$'diff <(ls /home/sice/ | grep a) <(ls | grep b)'
run_cmd $input_str
#both together
input_str=$'cat <(ls -al) > >(grep command)'
run_cmd $input_str
if [ $pass = true ]
then
    exit 0
else
    exit 1
fi
