#!/bin/zsh
diffFile=test_pipe.diff
pass=true
run_cmd() {
    #echo Processing Command: $1
    echo Processing Command: $1 >>& $diffFile
    diff <(/bin/zsh <<< $1 2>&1) <(../shell <<< $1 2>&1) >>& $diffFile
    check $1 $?
}
check() {
    if [ $2 -ne 0 ] 
    then
        echo -e "\033[1;31m Failed to run $1\033[0m"
        pass=false
    else
        echo -e "\033[1;32m $1 ran successfully\033[0m"
    fi
}
echo -e "\033[1;4;93m\ttest pipe\033[0m"
echo -e "\033[1;4;93m\ttest pipe\033[0m" > $diffFile
input_str=$'ls|cat'
run_cmd $input_str
input_str=$'ls|cat | grep a'
run_cmd $input_str
input_str=$'cat a | grep a'
run_cmd $input_str
input_str=$'cat testall | grep test | cat'
run_cmd $input_str
input_str=$'cat /usr/share/dict/words | grep o | head'
#run_cmd $input_str
input_str=$'cat /usr/share/dict/words | grep o | tail'
run_cmd $input_str
input_str=$'ls -al | grep test | wc'
run_cmd $input_str
if [ $pass = true ]
then
    exit 0
else 
    exit 1
fi
