#!/bin/zsh
diffFile=test_unsetenv.diff
pass=true
check() {
    if [ $2 -ne 0 ] 
    then
        echo -e "\033[1;31m Failed to run $1\033[0m"
        pass=false
    else
        echo -e "\033[1;32m $1 ran successfully\033[0m"
    fi
}
echo -e "\033[1;4;93m\ttest unsetenv \033[0m"
echo -e "\033[1;4;93m\ttest unsetenv \033[0m" > $diffFile
shell_in=$'setenv cbcasdf b\nprintenv\nunsetenv cbcasdf\nprintenv'
res=$(grep -c cbcasdf= <(../shell <<< "$shell_in" 2>&1))
echo Processing Command: $shell_in>>&$diffFile
flag=0
if [ $res -ne 1 ]
then
    flag=1
fi
check $shell_in $flag
shell_in=$'unsetenv asdf'
echo Processing Command: $shell_in>>&$diffFile
grep "unsetenv: variable not found" <(../shell <<< "$shell_in" 2>&1)
check $shell_in $?
shell_in=$'unsetenv asdf s'
echo Processing Command: $shell_in>>&$diffFile
grep "unsetenv: wrong number of arguments" <(../shell <<< "$shell_in" 2>&1)>>&$diffFile
check $shell_in $?
if [ $pass = true ]
then
    exit 0
else
    exit 1
fi
