#!/bin/zsh
diffFile=test_redirect_error.diff
pass=true
check() {
    if [ $2 -ne 0 ] 
    then
        echo -e "\033[1;31m Failed to run $1\033[0m"
        pass=false
    else
        echo -e "\033[1;32m $1 ran successfully\033[0m"
    fi
}
echo -e "\033[1;4;93m\ttest redirect error\033[0m"
echo -e "\033[1;4;93m\ttest redirect error\033[0m" > $diffFile
shell_in=$'ls -al testall 2> out1'
zsh_in=$'ls -al testall 2> out2'
rm -f out*
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out2) <(../shell <<< $shell_in 2>&1; cat out1) >>& $diffFile
check $shell_in $?
shell_in=$'ls randomfile 2> out1'
zsh_in=$'ls randomfile 2> out2'
rm -f out*
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out2) <(../shell <<< $shell_in 2>&1; cat out1) >>& $diffFile
check $shell_in $?
shell_in=$'grep randomfile a 2> out1'
zsh_in=$'grep randomfile a 2> out2'
rm -f out*
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out2) <(../shell <<< $shell_in 2>&1; cat out1) >>& $diffFile
check $shell_in $?
shell_in=$'rm aaaaasdfsds 2> out1'
zsh_in=$'rm aaaaasdfsds 2> out2'
rm -f out*
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out2) <(../shell <<< $shell_in 2>&1; cat out1) >>& $diffFile
check $shell_in $?
shell_in=$'sort a 2> out1'
zsh_in=$'sort a 2> out2'
rm -f out*
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out2) <(../shell <<< $shell_in 2>&1; cat out1) >>& $diffFile
check $shell_in $?
shell_in=$'head b 2> out1 2>out2 2>     out3'
zsh_in=$'head b 2> out4 2>out5 2>     out6'
rm -f out*
echo Processing Command: $shell_in>>$diffFile
diff --color -u <(/bin/zsh <<< $zsh_in 2>&1; cat out[4-6]) <(../shell <<< $shell_in 2>&1; cat out[1-3]) >>& $diffFile
check $shell_in $?
if [ $pass = true ]
then
    exit 0
else
    exit 1
fi
